[pytest]
testpaths = . ../independent/ffiam/pyffiam/tests
pythonpath = .. ../independent/ffiam/pyffiam/src
python_files = example_*.py test_*.py
python_classes = Example Test* *TestCase
python_functions = example_* test_*
markers = requires_cuda: skip when no CUDA runtime is present